Version update mphealth 3.1
OpenLiberty/draft-guide-microprofile-health pull request #162
Opened 2021-11-03 14:19 UTC by Kevcpro

2021-11-08 18:01 UTC, gkwan-ibm requested changes
@Kevcpro 
- ** What you’ll learn**
  - [x] need to update "MicroProfile offers checks for both liveness and readiness."
- **Try what you’ll build**
  - [x] "liveness, startup and readiness" -> "startup, liveness, and readiness"
- **Adding health checks to microservices**
  - [x] "The `@Startup` annotation in...", the hotspot `@Startup` highlights incorrectly
  - [ ] for startup, `90%` does not match to the SystemStartupCheck code
  - [ ] "The `@Liveness` annotation...", the hotsport `@Liveness` highlights incorrectly
  - [ ] "The `@Readiness` annotation ... `ApplicationScoped` ...", the hotsports `@Readiness` and `ApplicationScoped` highlight incorrectly

look like hotspots and file references after this section are incorrect. Cannot review.

2021-11-26 21:29 UTC, gkwan-ibm commented
hi @Kevcpro 
Would you update both startup classes in the finish, so that the status includes system load data as the liveness check?

2021-12-07 17:50 UTC, gkwan-ibm commented
hi @Kevcpro 
Because the testing env may have > 95% cpu usage, the test failed. Let remove the startup tests from the content and junit.

2022-01-07 13:24 UTC, ryan-storey approved these changes

2022-01-07 13:26 UTC, ryan-storey commented
System and Inventory Startup and Liveness checks have been modified to pass the tests ran via GitHub actions. Tests now pass consistently.

2022-01-11 15:11 UTC, pgunapal approved these changes
LGTM

2022-01-14 04:03 UTC, dmuelle requested changes
ID review, let me know if you have any questions. Thanks

2022-01-14 04:03 UTC, dmuelle commented on README.adoc
> +overall health status of the application, as well as the aggregated data of the startup, liveness
add a comma after liveness

...aggregated data of the startup, liveness, and readiness...

2022-01-14 04:03 UTC, dmuelle commented on README.adoc
> +All services must provide an implementation of the `HealthCheck` interface, that are used to
All services must provide an implementation of the `HealthCheck` interface, that are used to
verify their health.
--->
All services must provide an implementation of the `HealthCheck` interface, which is used to
verify their health.

2022-01-14 04:03 UTC, dmuelle commented on README.adoc
> +The [hotspot=Startup file=0]`@Startup` annotation indicates that this is a startup health check procedure.
is the procedure a bean? if so

The [hotspot=Startup file=0]`@Startup` annotation indicates that this bean is a startup health check procedure.

if not a bean- edit as needed to say what "this" is

2022-01-14 04:03 UTC, dmuelle commented on README.adoc
> +The [hotspot=Liveness file=1]`@Liveness` annotation indicates that this is a liveness health check procedure.
see previous comment re "this"

2022-01-14 04:03 UTC, dmuelle commented on README.adoc
> +The [hotspot=Readiness file=2]`@Readiness` annotation indicates that this particular bean is a readiness health check procedure.
don't need "particular" here

2022-01-14 04:03 UTC, dmuelle commented on README.adoc
> +In this case, you are simply checking if the server name is [hotspot=defaultServer file=2]`defaultServer` and
don't need "simply" here

2022-01-14 04:03 UTC, dmuelle commented on README.adoc
> +Overall, this is a very simple implementation of the [hotspot=healthCheckResponse file=2]`call()`
suggested edit

Overall, this is a very simple implementation of the [hotspot=healthCheckResponse file=2]`call()`
method. In a real environment, you would want to orchestrate more meaningful
health checks.
--->
This example is a very simple implementation of the [hotspot=healthCheckResponse file=2]`call()`
method. In a real environment, you would orchestrate more meaningful
health checks.

2022-01-14 04:03 UTC, dmuelle commented on README.adoc
> +For simplicity, the custom [hotspot=3 file=3]`io_openliberty_guides_inventory_inMaintenance`
edit suggestions

For simplicity, the custom [hotspot=3 file=3]`io_openliberty_guides_inventory_inMaintenance`
MicroProfile Config property, that is defined in the [hotspot file=3]`resources/CustomConfigSource.json`
file, is used to indicate whether the service is in maintenance.
--->
For simplicity, the custom [hotspot=3 file=3]`io_openliberty_guides_inventory_inMaintenance`
MicroProfile Config property, which is defined in the [hotspot file=3]`resources/CustomConfigSource.json`
file,  indicates whether the service is in maintenance.

2022-01-14 04:03 UTC, dmuelle commented on README.adoc
> +The tests may fail if your system's CPU or memory is high in usage. The status of the system will be `DOWN` if the CPU usage is over 95%, or the memory usage is over 90%.
The tests may fail if your system's CPU or memory is high in usage. The status of the system will be `DOWN` if the CPU usage is over 95%, or the memory usage is over 90%.
--->
The tests might fail if your system CPU or memory use is high. The status of the system is `DOWN` if the CPU usage is over 95%, or the memory usage is over 90%.

2022-01-14 17:13 UTC, gkwan-ibm commented on README.adoc
> +The [hotspot=Startup file=0]`@Startup` annotation indicates that this is a startup health check procedure.
I am not sure why before use the word "bean". I assume it implies "bean" = "class". Yes, all 3 classes are similar but for different health checks. So should say "...annotation indicates that this bean..." or "... annotation indicates that this class ..."?

2022-01-17 22:00 UTC, dmuelle requested changes

2022-01-17 22:00 UTC, dmuelle commented on README.adoc
> +The [hotspot=Startup file=0]`@Startup` annotation indicates that this is a startup health check procedure.
If "class" is correct for all 3 instances, I'd recommend that for consistency in all three cases, like:

The [hotspot=Startup file=0]@Startup annotation indicates that this class is a startup health check procedure.

2022-01-18 14:32 UTC, dmuelle approved these changes
LGTM, thanks

2022-01-18 16:53 UTC, gkwan-ibm approved these changes

2022-01-18 16:53 UTC, merged